version: '3.1'

services:

  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd4postgres
      POSTGRES_DB: identity
    ports:
      - 5432:5432
